// Phase 4' drift detection: CollectActualState reads the sudoers
// fragments from disk under scope.Path and parses them back into the
// canonical body shape that Plan emits. The result is byte-identical
// across runs given the same on-disk inputs (Items sorted by
// ResourceKind/ResourceRef, allow + deny lists lex-sorted).

package linux_sudo

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"statebound.dev/statebound/internal/connectors"
)

// CollectActualState walks scope.Path and parses every regular file as
// a sudoers fragment generated by this connector. Sub-directories,
// symlinks, and non-regular entries are skipped. A missing scope.Path
// is a user error (regular error). An empty directory is fine and
// returns an empty Items slice — that is "zero actual state", which
// Compare interprets as "everything desired is missing".
func (*Connector) CollectActualState(_ context.Context, scope connectors.CollectionScope) (*connectors.ActualState, error) {
	if scope.Path == "" {
		return nil, fmt.Errorf("linux-sudo collect: scope.Path is required")
	}

	info, err := os.Stat(scope.Path)
	if err != nil {
		return nil, fmt.Errorf("linux-sudo collect: stat %q: %w", scope.Path, err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("linux-sudo collect: %q is not a directory", scope.Path)
	}

	entries, err := os.ReadDir(scope.Path)
	if err != nil {
		return nil, fmt.Errorf("linux-sudo collect: read dir %q: %w", scope.Path, err)
	}

	absPath, err := filepath.Abs(scope.Path)
	if err != nil {
		// Fall back to the supplied path; absolutification is cosmetic.
		absPath = scope.Path
	}

	items := make([]connectors.ActualStateItem, 0, len(entries))
	for _, e := range entries {
		if !e.Type().IsRegular() {
			continue
		}
		full := filepath.Join(scope.Path, e.Name())
		raw, err := os.ReadFile(full)
		if err != nil {
			return nil, fmt.Errorf("linux-sudo collect: read %q: %w", full, err)
		}
		parsed := parseSudoersFragment(raw)
		entitlement := parsed.entitlement
		if entitlement == "" {
			// Fall back to the file basename so the item is still
			// addressable even if the header was stripped.
			entitlement = e.Name()
		}
		scopeName := parsed.scope
		if scopeName == "" {
			scopeName = "unknown"
		}
		body := map[string]any{
			"path":        full,
			"scope":       scopeName,
			"entitlement": entitlement,
			"as_user":     parsed.asUser,
			"content":     parsed.content,
			"allows":      parsed.allows,
			"denies":      parsed.denies,
		}
		items = append(items, connectors.ActualStateItem{
			ResourceKind: "linux.sudoers-fragment",
			ResourceRef:  fmt.Sprintf("%s:/etc/sudoers.d/%s", scopeName, entitlement),
			Body:         body,
		})
	}

	// Deterministic ordering: ResourceKind ASC, ResourceRef ASC.
	sort.SliceStable(items, func(i, j int) bool {
		if items[i].ResourceKind != items[j].ResourceKind {
			return items[i].ResourceKind < items[j].ResourceKind
		}
		return items[i].ResourceRef < items[j].ResourceRef
	})

	return &connectors.ActualState{
		ConnectorName:    connectorName,
		ConnectorVersion: connectorVersion,
		SourceRef:        "file://" + absPath,
		CollectedAt:      time.Now().UTC(),
		Items:            items,
	}, nil
}

// parsedFragment is the structured shape recovered from a sudoers
// fragment file. allows + denies are lex-sorted; content is the raw
// text with line endings normalised to "\n".
type parsedFragment struct {
	entitlement string
	scope       string
	asUser      string
	allows      []string
	denies      []string
	content     string
}

// parseSudoersFragment is a small line-oriented state machine. It
// recognises:
//
//   # Source: entitlement=<name> asset_scope=<scope> [approved_version=<n>]
//   %<entitlement> ALL=(<as_user>) <comma_or_semicolon_separated_allows>
//   %<entitlement> ALL=(<as_user>) !<deny>
//
// Multiple allow lines accumulate. Each non-! command runs through the
// same comma/semicolon split; deny lines record exactly one command.
// Unknown lines are tolerated (forward-compatibility).
func parseSudoersFragment(raw []byte) parsedFragment {
	// Normalise line endings: strip \r so CRLF inputs behave the same
	// as LF inputs without re-encoding the file.
	normalised := strings.ReplaceAll(string(raw), "\r\n", "\n")
	normalised = strings.ReplaceAll(normalised, "\r", "\n")

	out := parsedFragment{content: normalised}

	scanner := bufio.NewScanner(strings.NewReader(normalised))
	// A single sudoers line can be long if many commands are in one
	// allow rule. Bump the buffer cap above the default 64KiB.
	scanner.Buffer(make([]byte, 0, 1<<16), 1<<20)

	allowSet := make(map[string]struct{})
	denySet := make(map[string]struct{})

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "#") {
			parseSourceComment(line, &out)
			continue
		}
		if strings.HasPrefix(line, "%") {
			parseRuleLine(line, &out, allowSet, denySet)
			continue
		}
		// Unknown line: ignore.
	}

	for cmd := range allowSet {
		out.allows = append(out.allows, cmd)
	}
	sort.Strings(out.allows)
	for cmd := range denySet {
		out.denies = append(out.denies, cmd)
	}
	sort.Strings(out.denies)
	if out.allows == nil {
		out.allows = []string{}
	}
	if out.denies == nil {
		out.denies = []string{}
	}
	return out
}

// parseSourceComment recovers entitlement + scope from the standard
// header comment. Any unrecognised key=value pair is ignored.
func parseSourceComment(line string, out *parsedFragment) {
	body := strings.TrimSpace(strings.TrimPrefix(line, "#"))
	if !strings.HasPrefix(body, "Source:") {
		return
	}
	body = strings.TrimSpace(strings.TrimPrefix(body, "Source:"))
	for _, tok := range strings.Fields(body) {
		eq := strings.IndexByte(tok, '=')
		if eq <= 0 {
			continue
		}
		key, val := tok[:eq], tok[eq+1:]
		switch key {
		case "entitlement":
			out.entitlement = val
		case "asset_scope":
			out.scope = val
		}
	}
}

// parseRuleLine parses a single "%name ALL=(asUser) cmd1, cmd2" or
// "%name ALL=(asUser) !cmd" line, accumulating commands into the
// supplied sets.
func parseRuleLine(line string, out *parsedFragment, allows, denies map[string]struct{}) {
	// Find the "=(" delimiter for as_user.
	eqOpen := strings.Index(line, "=(")
	if eqOpen < 0 {
		return
	}
	rest := line[eqOpen+2:]
	closeParen := strings.IndexByte(rest, ')')
	if closeParen < 0 {
		return
	}
	asUser := strings.TrimSpace(rest[:closeParen])
	if out.asUser == "" {
		out.asUser = asUser
	}
	tail := strings.TrimSpace(rest[closeParen+1:])
	if tail == "" {
		return
	}
	// Split on comma OR semicolon — plan generator emits comma; honor
	// either separator for forward compat with hand-edited fragments.
	splitter := func(r rune) bool { return r == ',' || r == ';' }
	for _, raw := range strings.FieldsFunc(tail, splitter) {
		cmd := strings.TrimSpace(raw)
		if cmd == "" {
			continue
		}
		if strings.HasPrefix(cmd, "!") {
			denies[strings.TrimSpace(strings.TrimPrefix(cmd, "!"))] = struct{}{}
			continue
		}
		allows[cmd] = struct{}{}
	}
}
